[package]
name = "quilt"
authors = ["Nathaniel Fernandes <nathaniel.s.fernandes@gmail.com>"]
version = "0.1.1"
edition = "2021"

[dependencies]
common       = { path = "./common" }
parser       = { path = "./parser" }
bytecode     = { path = "./bytecode" }
compiler     = { path = "./compiler" }
interpreter  = { path = "./interpreter" }
disassembler = { path = "./disassembler" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"